name: im-cnn-env
channels:
  - pytorch
  - defaults
dependencies:
  - alabaster=0.7.11=py35_0
  - asn1crypto=0.24.0=py35_0
  - babel=2.6.0=py35_0
  - backcall=0.1.0=py35_0
  - binutils_impl_linux-64=2.28.1=had2808c_3
  - binutils_linux-64=7.2.0=had2808c_27
  - blas=1.0=mkl
  - bleach=2.1.3=py35_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.4.16=py35_0
  - cffi=1.11.5=py35h9745a5d_0
  - chardet=3.0.4=py35hb6e9ddf_1
  - cryptography=2.2.2=py35h14c3975_0
  - cudatoolkit=9.0=h13b8566_0
  - cudnn=7.1.2=cuda9.0_0
  - cycler=0.10.0=py35hc4d5149_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py35_0
  - docutils=0.14=py35hd11081d_0
  - entrypoints=0.2.3=py35h48174a2_2
  - expat=2.2.5=he0dffb1_0
  - fontconfig=2.12.6=h49f89f6_0
  - freetype=2.8=hab7d2ae_1
  - future=0.16.0=py35_2
  - gcc_impl_linux-64=7.2.0=habb00fd_3
  - gcc_linux-64=7.2.0=h550dcbe_27
  - glib=2.56.1=h000015b_0
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - gxx_impl_linux-64=7.2.0=hdf63c60_3
  - gxx_linux-64=7.2.0=h550dcbe_27
  - html5lib=1.0.1=py35h2f9c1c0_0
  - icu=58.2=h9c2bf20_1
  - idna=2.7=py35_0
  - imagesize=1.0.0=py35_0
  - intel-openmp=2018.0.3=0
  - ipykernel=4.8.2=py35_0
  - ipython=6.4.0=py35_0
  - ipython_genutils=0.2.0=py35hc9e07d0_0
  - ipywidgets=7.2.1=py35_0
  - jedi=0.12.0=py35_1
  - jinja2=2.10=py35h480ab6d_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py35h4395190_0
  - jupyter=1.0.0=py35_4
  - jupyter_client=5.2.3=py35_0
  - jupyter_console=5.2.0=py35h4044a63_1
  - jupyter_core=4.4.0=py35ha89e94b_0
  - kiwisolver=1.0.1=py35hcb1117a_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libgpuarray=0.7.6=h14c3975_0
  - libpng=1.6.34=hb9fc6fc_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - libtiff=4.0.9=he85c1e1_1
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - mako=1.0.7=py35h69899ea_0
  - markupsafe=1.0=py35h4f4fcf6_1
  - matplotlib=2.2.2=py35h0e671d2_1
  - mistune=0.8.3=py35h14c3975_1
  - mkl=2018.0.3=1
  - mkl-service=1.1.2=py35h0fc7090_4
  - mkl_fft=1.0.4=py35h4414c95_1
  - mkl_random=1.0.1=py35h4414c95_1
  - nbconvert=5.3.1=py35hc5194e3_0
  - nbformat=4.4.0=py35h12e6e07_0
  - nccl=1.3.5=cuda9.0_0
  - ncurses=6.1=hf484d3e_0
  - ninja=1.8.2=py35h6bb024c_1
  - nose=1.3.7=py35hdc64897_2
  - notebook=5.5.0=py35_0
  - numpy=1.14.5=py35hcd700cb_0
  - numpy-base=1.14.5=py35hdbf6ddf_0
  - olefile=0.46=py35_0
  - openssl=1.0.2o=h20670df_0
  - packaging=17.1=py35_0
  - pandoc=2.2.1=h629c226_0
  - pandocfilters=1.4.2=py35h1565a15_1
  - parso=0.2.1=py35_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py35_0
  - pickleshare=0.7.4=py35hd57304d_0
  - pillow=5.1.0=py35h3deb7b8_0
  - pip=10.0.1=py35_0
  - prompt_toolkit=1.0.15=py35hc09de7a_0
  - ptyprocess=0.6.0=py35_0
  - pycparser=2.18=py35h61b3040_1
  - pygments=2.2.0=py35h0f41973_0
  - pygpu=0.7.6=py35h3010b51_0
  - pymongo=3.4.0=py35_0
  - pyopenssl=18.0.0=py35_0
  - pyparsing=2.2.0=py35h041ed72_1
  - pyqt=5.9.2=py35h751905a_0
  - pysocks=1.6.8=py35_0
  - python=3.5.5=hc3d631a_4
  - python-dateutil=2.7.3=py35_0
  - pytz=2018.5=py35_0
  - pyzmq=17.0.0=py35h14c3975_0
  - qt=5.9.5=h7e424d6_0
  - qtconsole=4.3.1=py35h4626a06_0
  - readline=7.0=ha6073c6_4
  - requests=2.19.1=py35_0
  - scikit-learn=0.19.1=py35hbf1f462_0
  - scipy=1.1.0=py35hfc37229_0
  - send2trash=1.5.0=py35_0
  - setuptools=39.2.0=py35_0
  - simplegeneric=0.8.1=py35_2
  - sip=4.19.8=py35hf484d3e_0
  - six=1.11.0=py35h423b573_1
  - snowballstemmer=1.2.1=py35h5435977_0
  - sphinx=1.7.5=py35_0
  - sphinxcontrib=1.0=py35hcb7efd2_1
  - sphinxcontrib-websupport=1.1.0=py35_1
  - sqlalchemy=1.2.11=py35h7b6447c_0
  - sqlite=3.24.0=h84994c4_0
  - terminado=0.8.1=py35_1
  - testpath=0.3.1=py35had42eaf_0
  - theano=1.0.2=py35h6bb024c_0
  - tk=8.6.7=hc745277_3
  - torchvision=0.2.1=py35_0
  - tornado=5.0.2=py35_0
  - traitlets=4.3.2=py35ha522a97_0
  - urllib3=1.23=py35_0
  - wcwidth=0.1.7=py35hcd08066_0
  - webencodings=0.5.1=py35hb6cf162_1
  - wheel=0.31.1=py35_0
  - widgetsnbextension=3.2.1=py35_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.2.5=h439df22_0
  - zlib=1.2.11=ha838bed_2
  - cuda80=1.0=h205658b_0
  - pytorch=0.4.1=py35_py27__9.0.176_7.1.2_2
  - pip:
    - cython==0.29.6
    - matplotlib2tikz==0.6.18
    - protobuf==3.7.0
    - sewar==0.4
    - tensorboardx==1.4
    - torch==0.4.1.post2
prefix: /home/rck/.conda/envs/nn-env

